import { ProductCategoryType, ProductType } from "@/@types/product.type";

export const PRODUCT_CATEGORY_LIST: ProductCategoryType[] = [
    {
        id: 1,
        name: 'Desk',
        description: "Desk for Workspaces",
    }, {
        id: 2,
        name: "Monitor",
        description: "Monitor Display",
    }, {
        id: 3,
        name: "Chair",
        description: "Chair",
    }, {
        id: 4,
        name: "Accessories",
        description: "Accessories",
    }, {
        id: 5,
        name: "Interior",
        description: "Interior",
    }
];

export const PRODUCT_LIST: ProductType[] = [
    {
        id: 1,
        name: "Wooden Desk",
        description: "Modern minimalist wooden desk for productive workspaces.",
        product_category_id: 1,
        product_category: PRODUCT_CATEGORY_LIST[0],
        thumbnail: "img/desk/standard-wooden-desk.svg",
        status: "ACTIVE",
        stock: 12,
        price: 1200000,
        render_width: 400,
        render_height: 200,
        product_type: "SINGLE",
    },
    {
        id: 2,
        name: "Wooden Desk with Drawer",
        description: "Modern minimalist wooden desk for productive workspaces with big drawer",
        product_category_id: 1,
        product_category: PRODUCT_CATEGORY_LIST[0],
        thumbnail: "img/desk/wooden-desk-with-drawer1.svg",
        status: "ACTIVE",
        stock: 8,
        price: 1500000,
        product_type: "SINGLE",
        render_width: 400,
        render_height: 200,
    },
    {
        id: 3,
        name: "Wooden Desk with Multiple Drawer",
        description: "Modern minimalist wooden desk for productive workspaces.",
        product_category_id: 1,
        product_category: PRODUCT_CATEGORY_LIST[0],
        thumbnail: "img/desk/wooden-desk-with-drawer2.svg",
        status: "ACTIVE",
        stock: 10,
        price: 1500000,
        product_type: "SINGLE",
        render_width: 400,
        render_height: 200,
    },
    {
        id: 4,
        name: "24 Inch Monitor",
        description: "Full HD IPS monitor for daily productivity.",
        product_category_id: 2,
        product_category: PRODUCT_CATEGORY_LIST[1],
        thumbnail: "img/monitor/black-curve.svg",
        status: "ACTIVE",
        stock: 15,
        price: 1800000,
        product_type: "MULTIPLE",
        render_width: 120,
        render_height: 120,
    },
    {
        id: 5,
        name: "UltraWide Curved Monitor",
        description: "Curved ultrawide monitor for multitasking.",
        product_category_id: 2,
        product_category: PRODUCT_CATEGORY_LIST[1],
        thumbnail: "img/monitor/red-modern.svg",
        status: "ACTIVE",
        stock: 6,
        price: 2000000,
        product_type: "MULTIPLE",
        render_width: 120,
        render_height: 120,
    },
    {
        id: 6,
        name: "4K Ultra Wide Monitor",
        description: "Ultrawide Monitor with 4K Support",
        product_category_id: 2,
        product_category: PRODUCT_CATEGORY_LIST[1],
        thumbnail: "img/monitor/blue-wide.svg",
        status: "ACTIVE",
        stock: 9,
        price: 2800000,
        product_type: "MULTIPLE",
        render_width: 120,
        render_height: 120,
    },
    {
        id: 7,
        name: "Standard Office Chair",
        description: "Comfortable chair for working",
        product_category_id: 3,
        product_category: PRODUCT_CATEGORY_LIST[2],
        thumbnail: "img/chair/standard-chair.svg",
        status: "ACTIVE",
        stock: 14,
        price: 1400000,
        product_type: "SINGLE",
        render_width: 160,
        render_height: 160,
    },
    {
        id: 8,
        name: "Office Chair Pro",
        description: "Comfortable Office Chair",
        product_category_id: 3,
        product_category: PRODUCT_CATEGORY_LIST[2],
        thumbnail: "img/chair/office-chair.svg",
        status: "ACTIVE",
        stock: 11,
        price: 2200000,
        product_type: "SINGLE",
        render_width: 160,
        render_height: 160,
    },
    {
        id: 9,
        name: "Executive Leather Chair",
        description: "Premium leather chair for executive workspaces.",
        product_category_id: 3,
        product_category: PRODUCT_CATEGORY_LIST[2],
        thumbnail: "img/chair/pro-chair.svg",
        status: "ACTIVE",
        stock: 5,
        price: 3800000,
        product_type: "SINGLE",
        render_width: 160,
        render_height: 160,
    },
    {
        id: 10,
        name: "Indoor Plant",
        description: "A pot of indoor plant",
        product_category_id: 4,
        product_category: PRODUCT_CATEGORY_LIST[3],
        thumbnail: "/img/accessories/single-plant.svg",
        status: "ACTIVE",
        stock: 25,
        price: 20000,
        product_type: "MULTIPLE",
        render_width: 80,
        render_height: 80,
    },
    {
        id: 11,
        name: "Potted Indoor Plant",
        description: "Long Potted plant for indoor",
        product_category_id: 4,
        product_category: PRODUCT_CATEGORY_LIST[3],
        thumbnail: "/img/accessories/multiple-plant.svg",
        status: "ACTIVE",
        stock: 18,
        price: 40000,
        product_type: "MULTIPLE",
        render_width: 200,
        render_height: 140,
    },
    {
        id: 12,
        name: "Desk Lamp",
        description: "Desk lamp for lighting",
        product_category_id: 4,
        product_category: PRODUCT_CATEGORY_LIST[3],
        thumbnail: "/img/accessories/desk-lamp.svg",
        status: "ACTIVE",
        stock: 20,
        price: 15000,
        product_type: "MULTIPLE",
        render_width: 120,
        render_height: 120,
    },
    {
        id: 13,
        name: "Printer",
        description: "Printer for office",
        product_category_id: 4,
        product_category: PRODUCT_CATEGORY_LIST[3],
        thumbnail: "/img/accessories/printer.svg",
        status: "ACTIVE",
        stock: 30,
        price: 150000,
        product_type: "MULTIPLE",
        render_width: 140,
        render_height: 140,
    },
    {
        id: 14,
        name: "Speaker",
        description: "Speaker for audio",
        product_category_id: 4,
        product_category: PRODUCT_CATEGORY_LIST[3],
        thumbnail: "/img/accessories/speaker.svg",
        status: "ACTIVE",
        stock: 7,
        price: 100000,
        product_type: "MULTIPLE",
        render_width: 120,
        render_height: 120,
    },
    {
        id: 15,
        name: "Standing Speaker",
        description: "Speaker standing for audio",
        product_category_id: 4,
        product_category: PRODUCT_CATEGORY_LIST[3],
        thumbnail: "/img/accessories/speaker-pro.svg",
        status: "ACTIVE",
        stock: 13,
        price: 200000,
        product_type: "MULTIPLE",
        render_width: 140,
        render_height: 140,
    },
    {
        id: 16,
        name: "Small Cabinet",
        description: "Small Cabinet for storing small items",
        product_category_id: 5,
        product_category: PRODUCT_CATEGORY_LIST[4],
        thumbnail: "/img/accessories/small-cabinet.svg",
        status: "ACTIVE",
        stock: 13,
        price: 200000,
        product_type: "MULTIPLE",
        render_width: 320,
        render_height: 240,
    },
    {
        id: 17,
        name: "Multi Cubic Cabinet",
        description: "4 Cubic Storage Cabinet",
        product_category_id: 5,
        product_category: PRODUCT_CATEGORY_LIST[4],
        thumbnail: "/img/accessories/multi-cabinet.svg",
        status: "ACTIVE",
        stock: 13,
        price: 350000,
        product_type: "MULTIPLE",
        render_width: 320,
        render_height: 320,
    },
    {
        id: 18,
        name: "Bookshelf",
        description: "Standard bookshelf for storage",
        product_category_id: 5,
        product_category: PRODUCT_CATEGORY_LIST[4],
        thumbnail: "/img/accessories/bookshelf2.svg",
        status: "ACTIVE",
        stock: 5,
        price: 400000,
        product_type: "MULTIPLE",
        render_width: 300,
        render_height: 400,
    },
    {
        id: 19,
        name: "Bookshelf with Drawer",
        description: "Bookshelf for storage with drawer",
        product_category_id: 5,
        product_category: PRODUCT_CATEGORY_LIST[4],
        thumbnail: "/img/accessories/bookshelf.svg",
        status: "ACTIVE",
        stock: 5,
        price: 500000,
        product_type: "MULTIPLE",
        render_width: 300,
        render_height: 400,
    },
];